name: Signature by email
description: Sign the petition by email
labels: [add-signature-email]
body:
- type: input
  id: name
  attributes:
    label: Your name
  validations:
    required: true
- type: input
  id: email
  attributes:
    label: Your email
  validations:
    required: true
