name: Signature
description: Sign the petition
labels: [add-signature]
body:
- type: input
  id: name
  attributes:
    label: Your name
  validations:
    required: true
- type: input
  id: email
  attributes:
    label: Your email
  validations:
    required: false
- type: textarea
  id: signature
  attributes:
    label: Your signature
  validations:
    required: true

