name: Sign by Issuue

on:
  workflow_dispatch:
    branches:
    - main

jobs:
  test_issue_tracker:
    runs-on: ubuntu-latest
    name: A job to test issue tracker
    steps:
    - name: Checkout
      uses: actions/checkout@v1
    - name: Track issues
      id: tracking
      uses: freethem-petition/sign-by-issue-action@master
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
