name: Sign by Issuue

on:
  workflow_dispatch:
    branches:
    - main

jobs:
  test_issue_tracker:
    runs-on: ubuntu-latest
    name: A job to add signatures to statement
    steps:
    - name: Checkout
      uses: actions/checkout@v1
    - name: Extract signatures
      id: signatures
      uses: freethem-petition/sign-by-issue-action@master
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
    - name: Create Pull Request
      uses: peter-evans/create-pull-request@v4
      with:
        branch: add-signatures
        branch-suffix: timestamp
        base: main
        add-paths: |
          SIGNATURES/*.sig
          STATEMENT/SHA256SUMS.asc
